# Numpy套件

In [1]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
#numpy套件ndarray型態,提供elLLement-wist的操作
import numpy as np
a_ndarray=np.array([1,2,3,4,5])
print(a_ndarray*3)

[ 3  6  9 12 15]


In [3]:
print(type(a_ndarray))
print(a_ndarray.ndim) #ndarray的維度
print(a_ndarray.shape) #ndarray的shape
print(a_ndarray.dtype) #ndarray的資料型態

<class 'numpy.ndarray'>
1
(5,)
int32


In [4]:
z=np.zeros(6)
print(z) #6個元素都為0的1d ndarray
print(np.zeros((2,6))) #12個元素都為0的2d ndarray
print(np.empty(((2,6)))) #24個元素都未初始化的值
print(np.arange(10)) #10個元素為0-9的1d ndarray

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[0 1 2 3 4 5 6 7 8 9]


# Ndarray的進階操作

In [5]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [6]:
#2維ndarray取值
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:]) #第二列資料
print(my_2d_array[:,1]) #第二欄資料
print(my_2d_array[1,1]) #第二列第二欄的資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [9]:
#假設有六個組別"modern web","devops","cloud",
#"big data","security","自我挑戰組"
#其參加人數分別為55,8,19,14,6,71人
groups=['modern web','devops','cloud','big data','security','自我挑戰組']
irponman=[55,8,19,14,6,71]
groups_array=np.array(groups)
irponman_array=np.array(irponman)
print(groups_array)
print(irponman_array)

['modern web' 'devops' 'cloud' 'big data' 'security' '自我挑戰組']
[55  8 19 14  6 71]


In [12]:
#用人數去篩選組別
print(irponman_array>=10)
print(groups_array[irponman_array>=10])
print(groups_array!="自我挑戰組")
print(irponman_array[groups_array!="自我挑戰組"])

[ True False  True  True False  True]
['modern web' 'cloud' 'big data' '自我挑戰組']
[ True  True  True  True  True False]
[55  8 19 14  6]


# Nsarray轉置

In [14]:
my_1d_array=np.arange(10)
print(my_1d_array)
my_2d_array=my_1d_array.reshape((2,5))
print(my_2d_array)
print(my_2d_array.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [15]:
#ndarray nan(空值)
nan_array=np.array([56,8,19,14,6,np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]
